# Generated by Django 4.0.6 on 2023-12-04 00:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('data_edicao', models.DateTimeField(default=datetime.datetime(2023, 12, 4, 0, 11, 39, 443576, tzinfo=utc))),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('ano', models.CharField(max_length=10)),
                ('emprestado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('data_edicao', models.DateTimeField(default=datetime.datetime(2023, 12, 4, 0, 11, 39, 444604, tzinfo=utc))),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=200)),
                ('emprestado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('data_edicao', models.DateTimeField(default=datetime.datetime(2023, 12, 4, 0, 11, 39, 447026, tzinfo=utc))),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmprestimoLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('devolucao', models.DateTimeField(auto_now=True)),
                ('data_edicao', models.DateTimeField(default=datetime.datetime(2023, 12, 4, 0, 11, 39, 445470, tzinfo=utc))),
                ('emprestimo', models.BooleanField(default=True)),
                ('contato', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='acervo.contato')),
                ('livro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='acervo.livro')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmprestimoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('devolucao', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2023, 12, 4, 0, 11, 39, 448040, tzinfo=utc))),
                ('emprestado', models.BooleanField(default=True)),
                ('contato', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='acervo.contato')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='acervo.item')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
