# Generated by Django 4.0.6 on 2023-12-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='foto_capa',
            field=models.ImageField(blank=True, null=True, upload_to='media/capas/'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_edicao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='emprestimoitem',
            name='data_criacao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='emprestimolivro',
            name='data_edicao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_edicao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_edicao',
            field=models.DateTimeField(),
        ),
    ]
