# Generated by Django 4.0.6 on 2023-12-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_livro_foto_capa_alter_contato_data_edicao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='foto_capa',
            new_name='fotodacapa',
        ),
    ]
