# Generated by Django 4.0.6 on 2024-01-08 14:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acervo', '0004_remove_livro_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emp', models.DateField(default=datetime.date.today)),
                ('data_dev', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emprestimolivro',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='emprestimolivro',
            name='livro',
        ),
        migrations.RemoveField(
            model_name='emprestimolivro',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='data_edicao',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='item',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='item',
            name='data_edicao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='data_edicao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='fotodacapa',
        ),
        migrations.AddField(
            model_name='contato',
            name='nome_cont',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='contato',
            name='telefone',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='livro',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='emprestado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livro',
            name='emprestado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='EmprestimoItem',
        ),
        migrations.DeleteModel(
            name='EmprestimoLivro',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.contato'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acervo.item'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acervo.livro'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
