# Generated by Django 4.0.6 on 2024-01-08 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0006_livro_fotocapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_dev',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_emp',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
