# Generated by Django 4.0.6 on 2024-01-08 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0007_remove_emprestimo_data_dev_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_emprestimo',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_dev',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_emp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
